#!/usr/bin/env bash

ESC=$(printf "\033")
SEMVERS=("patch" "minor" "major")

function select_option {
    # little helpers for terminal print control and key input
    cursor_blink_on()  { printf "$ESC[?25h"; }
    cursor_blink_off() { printf "$ESC[?25l"; }
    cursor_to()        { printf "$ESC[$1;${2:-1}H"; }
    print_option()     { printf "  $1"; }
    print_selected()   { printf "$ESC[36m❯ $1$ESC[0m"; }
    get_cursor_row()   { IFS=';' read -sdR -p $'\E[6n' ROW COL; echo ${ROW#*[}; }
    key_input()        { read -s -n3 key 2>/dev/null >&2
                         if [[ $key = $ESC[A ]]; then echo up;    fi
                         if [[ $key = $ESC[B ]]; then echo down;  fi
                         if [[ $key = ""     ]]; then echo enter; fi; }

    # initially print empty new lines (scroll down if at bottom of screen)
    for opt; do printf "\n"; done

    # determine current screen position for overwriting the options
    local lastrow=`get_cursor_row`
    local startrow=$(($lastrow - $#))

    # ensure cursor and input echoing back on upon a ctrl+c during read -s
    trap "cursor_blink_on; stty echo; printf '\n'; exit" 2
    cursor_blink_off

    local selected=0
    while true; do
        # print options by overwriting the last lines
        local idx=0
        for opt; do
            cursor_to $(($startrow + $idx))
            if [ $idx -eq $selected ]; then
                print_selected "$opt"
            else
                print_option "$opt"
            fi
            ((idx++))
        done

        # user key control
        case `key_input` in
            enter) break;;
            up)    ((selected--));
                   if [ $selected -lt 0 ]; then selected=$(($# - 1)); fi;;
            down)  ((selected++));
                   if [ $selected -ge $# ]; then selected=0; fi;;
        esac
    done

    # cursor position back to normal
    cursor_to $lastrow
    # clear all
    for opt; do
        printf "\e[K\e[1A"
    done
    printf "\e[K\e[1A\e[K"
    cursor_blink_on

    return $selected
}

echo -e "\e[1mSelect semver version\e[21m \e[2m(use arrow keys)\e[22m"
select_option "${SEMVERS[@]}"
npm version ${SEMVERS[$?]}
TAG=$(git describe --tags)
rm -rfd {node_modules,dist,public/css/index.css,public/js}
npm i && npm run build
git add --all
git commit -m "Update package version to $TAG"
git push origin master
git push origin master --tags
